[package]
name = "aptos_learnings"
version = "1.0.0"
authors = []

[addresses]
MyAccount = "_"
Admin = "_"
LotteryAt = "0x140be45bdf12009d4e08a886f89c6dec37d03f94604095d8bc7f885d078dfb70"
Origin = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
